# Generated by Django 5.1 on 2024-08-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUpLogin', '0002_remove_user_checkid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True, verbose_name=True),
            preserve_default=False,
        ),
    ]
