# Generated by Django 5.1 on 2024-08-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUpLogin', '0004_alter_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ammount',
            field=models.PositiveIntegerField(),
        ),
    ]
