# Generated by Django 5.1 on 2024-08-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUpLogin', '0007_userpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpdf',
            name='pdf_file',
            field=models.CharField(max_length=200),
        ),
    ]
