# Generated by Django 5.1 on 2024-08-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signUpLogin', '0008_alter_userpdf_pdf_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpdf',
            old_name='pdf_file',
            new_name='pdf_file_path',
        ),
    ]
